services:

  mlflow-tracking-server:
    image: ghcr.io/mlflow/mlflow
    command: mlflow ui --port 5000 --host 0.0.0.0 --backend-store-uri ./mlruns --artifacts-destination ./mlruns
    volumes:
      - ./mlruns:/mlruns
    container_name: mlflow-tracking
    ports:
      - 5000:5000
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 5

  diabetes-prediction-service:
    build:
      context: .
      dockerfile: Dockerfile.Service
      tags:
        - diabetes-prediction-service
        - ghcr.io/marquesr89/diabetes-prediction-service
    image: diabetes-prediction-service
    container_name: diabetes-prediction-service
    ports:
      - 5002:5002

  diabetes-prediction-ui:
    build:
      context: .
      dockerfile: Dockerfile.UI
      tags:
        - diabetes-prediction-ui
        - ghcr.io/marquesr89/diabetes-prediction-ui
    image: diabetes-prediction-ui
    container_name: diabetes-prediction-ui
    ports:
      - 5003:5003