FROM python:3.12

WORKDIR /app

LABEL org.opencontainer.imagem.source https://github.com/marquesr89/OML-aula

COPY frontend/form.html index.html

EXPOSE 5003

CMD ["python", "-m", "http.server", "5003"]